- name: Create user
  hosts: web
  become: yes 
  tasks:
    - name: check if user exists
      ansible.builtin.command: id expense
      register: user
      ignore_errors: true

    - name: create user if not exists
      ansible.builtin.user:
        name: expense
        state: present
      when: user.rc != 0


      



