- name: functions or filters
  hosts: local
  connection: local
  tasks:
    - name: print default variable
      debug:
        msg: "i am {{ name | default('vamsi') }}"
    
    - name: convert to upper case
      vars:
        role: "devops"
      debug:
        msg: "I am {{ role | upper }}"

    - name: replace age 
      vars:
        age: 25
      debug:
        msg: "i am {{ age | replace('age','45') }}"

    - name: sort the list
      debug:
        msg: "{{ [3, 5, 2, 4, 1] | sort }}"
    
    - name: remove duplicates
      debug:
        msg: "{{[ 4, 4, 2, 2, 1, 1 ] | sort | unique }}"

    - name: converts dict into list of items
      vars:
        my_dict:
          key1: "value1"
          key2: "value2"
      debug:
        msg: "{{ my_dict | dict2items }}"

    - name: convert list of items back to dictionary
      vars:
        my_list:
        - {key: 'key1', value: 'value1'}
        - {key: 'key2', value: 'value2'}
      debug:
        msg: "{{ my_list | items2dict }}"

    

