- name: launch an ec2-instance
  hosts: local
  connection: local
  vars:
    vpc_subnet_id: subnet-0618adb1a1197676b
    security_group: sg-0ceadcb893f8e3930
    image_id: ami-09c813fb71547fc4f
    instances:
    - mysql
    - backend
    - frontend

  tasks:
  - name: create ec2-instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: "t2.micro"
      vpc_subnet_id:  "{{ vpc_subnet_id }}"
      security_group: "{{ security_group }}"
      image_id: "{{ image_id }}"
    loop: "{{ instances }}"
    register: ec2_instances



