- name: variables
  hosts: webservers
  vars: 
    name: "i am vamsi"
    role: "devops engineer"
  tasks:
    - name: name and job role
      ansible.builtin.debug:
        msg: "Hi {{name}}, and i work as a {{role}} for amazon"
    - name: name and job role
      vars:
        name: "Battu"
      ansible.builtin.debug:
        msg: "Hi {{name}}, and i work as a {{role}} for amazon"