- name: prompt users to input
  hosts: webservers
  vars_prompt:
    - name: "username"
      prompt: "Enter your username"
      private: no
    - name: "password"
      prompt: "enter your password"
      private: no
  
  tasks:
    - name: display username and password
      ansible.builtin.debug:
        msg: "username is {{username}} and password is {{password}}"
